/* root layout: 在這邊設定會影響所有頁面, routes，不會re-render。可放fonts, styles, metadata */
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "沖縄旅行202412",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
